var mongoose = require('mongoose');

var SocksSchema = mongoose.Schema({
    ip: String,
    user: String,
    pass: String,
    country: String,
    live: String,
    fresh: String,
    bl: String,
    used: Boolean
});

/**
 * Static method
 */

SocksSchema.statics = {
    findByIp: function(ip, cb) {
        return this.find({
            ip: ip
        }).exec(cb);
    },
    getAllSocks: function(cb) {
        return this.find({}).exec(cb);
    },
    countNotUsed: function(cb) {
        var query = {
            'used': {
                '$ne': true
            }
        };
        return this.count(query).exec(cb);
    },
    getAllSocksNonUsed: function(cb) {
        var query = {
            'used': {
                '$ne': true
            }
        };
        return this.find(query).exec(cb);
    },
    getRandomSocks: function(r, cb) {
        var query = {
            'used': {
                '$ne': true
            }
        };
        return this.find(query).limit(1).skip(r).exec(cb);
    }
};

module.exports = {
    AF: mongoose.model('AF-Socks', SocksSchema, 'AF-Socks'),
    AL: mongoose.model('AL-Socks', SocksSchema, 'AL-Socks'),
    DZ: mongoose.model('DZ-Socks', SocksSchema, 'DZ-Socks'),
    AS: mongoose.model('AS-Socks', SocksSchema, 'AS-Socks'),
    AD: mongoose.model('AD-Socks', SocksSchema, 'AD-Socks'),
    AO: mongoose.model('AO-Socks', SocksSchema, 'AO-Socks'),
    AI: mongoose.model('AI-Socks', SocksSchema, 'AI-Socks'),
    AQ: mongoose.model('AQ-Socks', SocksSchema, 'AQ-Socks'),
    AG: mongoose.model('AG-Socks', SocksSchema, 'AG-Socks'),
    AR: mongoose.model('AR-Socks', SocksSchema, 'AR-Socks'),
    AM: mongoose.model('AM-Socks', SocksSchema, 'AM-Socks'),
    AW: mongoose.model('AW-Socks', SocksSchema, 'AW-Socks'),
    AU: mongoose.model('AU-Socks', SocksSchema, 'AU-Socks'),
    AT: mongoose.model('AT-Socks', SocksSchema, 'AT-Socks'),
    AZ: mongoose.model('AZ-Socks', SocksSchema, 'AZ-Socks'),
    BS: mongoose.model('BS-Socks', SocksSchema, 'BS-Socks'),
    BH: mongoose.model('BH-Socks', SocksSchema, 'BH-Socks'),
    BD: mongoose.model('BD-Socks', SocksSchema, 'BD-Socks'),
    BB: mongoose.model('BB-Socks', SocksSchema, 'BB-Socks'),
    BY: mongoose.model('BY-Socks', SocksSchema, 'BY-Socks'),
    BE: mongoose.model('BE-Socks', SocksSchema, 'BE-Socks'),
    BZ: mongoose.model('BZ-Socks', SocksSchema, 'BZ-Socks'),
    BJ: mongoose.model('BJ-Socks', SocksSchema, 'BJ-Socks'),
    BM: mongoose.model('BM-Socks', SocksSchema, 'BM-Socks'),
    BT: mongoose.model('BT-Socks', SocksSchema, 'BT-Socks'),
    BO: mongoose.model('BO-Socks', SocksSchema, 'BO-Socks'),
    BA: mongoose.model('BA-Socks', SocksSchema, 'BA-Socks'),
    BW: mongoose.model('BW-Socks', SocksSchema, 'BW-Socks'),
    BR: mongoose.model('BR-Socks', SocksSchema, 'BR-Socks'),
    IO: mongoose.model('IO-Socks', SocksSchema, 'IO-Socks'),
    VG: mongoose.model('VG-Socks', SocksSchema, 'VG-Socks'),
    BN: mongoose.model('BN-Socks', SocksSchema, 'BN-Socks'),
    BG: mongoose.model('BG-Socks', SocksSchema, 'BG-Socks'),
    BF: mongoose.model('BF-Socks', SocksSchema, 'BF-Socks'),
    BI: mongoose.model('BI-Socks', SocksSchema, 'BI-Socks'),
    KH: mongoose.model('KH-Socks', SocksSchema, 'KH-Socks'),
    CM: mongoose.model('CM-Socks', SocksSchema, 'CM-Socks'),
    CA: mongoose.model('CA-Socks', SocksSchema, 'CA-Socks'),
    CV: mongoose.model('CV-Socks', SocksSchema, 'CV-Socks'),
    KY: mongoose.model('KY-Socks', SocksSchema, 'KY-Socks'),
    CF: mongoose.model('CF-Socks', SocksSchema, 'CF-Socks'),
    TD: mongoose.model('TD-Socks', SocksSchema, 'TD-Socks'),
    CL: mongoose.model('CL-Socks', SocksSchema, 'CL-Socks'),
    CN: mongoose.model('CN-Socks', SocksSchema, 'CN-Socks'),
    CX: mongoose.model('CX-Socks', SocksSchema, 'CX-Socks'),
    CC: mongoose.model('CC-Socks', SocksSchema, 'CC-Socks'),
    CO: mongoose.model('CO-Socks', SocksSchema, 'CO-Socks'),
    KM: mongoose.model('KM-Socks', SocksSchema, 'KM-Socks'),
    CK: mongoose.model('CK-Socks', SocksSchema, 'CK-Socks'),
    CR: mongoose.model('CR-Socks', SocksSchema, 'CR-Socks'),
    HR: mongoose.model('HR-Socks', SocksSchema, 'HR-Socks'),
    CU: mongoose.model('CU-Socks', SocksSchema, 'CU-Socks'),
    CW: mongoose.model('CW-Socks', SocksSchema, 'CW-Socks'),
    CY: mongoose.model('CY-Socks', SocksSchema, 'CY-Socks'),
    CZ: mongoose.model('CZ-Socks', SocksSchema, 'CZ-Socks'),
    CD: mongoose.model('CD-Socks', SocksSchema, 'CD-Socks'),
    DK: mongoose.model('DK-Socks', SocksSchema, 'DK-Socks'),
    DJ: mongoose.model('DJ-Socks', SocksSchema, 'DJ-Socks'),
    DM: mongoose.model('DM-Socks', SocksSchema, 'DM-Socks'),
    DO: mongoose.model('DO-Socks', SocksSchema, 'DO-Socks'),
    TL: mongoose.model('TL-Socks', SocksSchema, 'TL-Socks'),
    EC: mongoose.model('EC-Socks', SocksSchema, 'EC-Socks'),
    EG: mongoose.model('EG-Socks', SocksSchema, 'EG-Socks'),
    SV: mongoose.model('SV-Socks', SocksSchema, 'SV-Socks'),
    GQ: mongoose.model('GQ-Socks', SocksSchema, 'GQ-Socks'),
    ER: mongoose.model('ER-Socks', SocksSchema, 'ER-Socks'),
    EE: mongoose.model('EE-Socks', SocksSchema, 'EE-Socks'),
    ET: mongoose.model('ET-Socks', SocksSchema, 'ET-Socks'),
    FK: mongoose.model('FK-Socks', SocksSchema, 'FK-Socks'),
    FO: mongoose.model('FO-Socks', SocksSchema, 'FO-Socks'),
    FJ: mongoose.model('FJ-Socks', SocksSchema, 'FJ-Socks'),
    FI: mongoose.model('FI-Socks', SocksSchema, 'FI-Socks'),
    FR: mongoose.model('FR-Socks', SocksSchema, 'FR-Socks'),
    PF: mongoose.model('PF-Socks', SocksSchema, 'PF-Socks'),
    GA: mongoose.model('GA-Socks', SocksSchema, 'GA-Socks'),
    GM: mongoose.model('GM-Socks', SocksSchema, 'GM-Socks'),
    GE: mongoose.model('GE-Socks', SocksSchema, 'GE-Socks'),
    DE: mongoose.model('DE-Socks', SocksSchema, 'DE-Socks'),
    GH: mongoose.model('GH-Socks', SocksSchema, 'GH-Socks'),
    GI: mongoose.model('GI-Socks', SocksSchema, 'GI-Socks'),
    GR: mongoose.model('GR-Socks', SocksSchema, 'GR-Socks'),
    GL: mongoose.model('GL-Socks', SocksSchema, 'GL-Socks'),
    GD: mongoose.model('GD-Socks', SocksSchema, 'GD-Socks'),
    GU: mongoose.model('GU-Socks', SocksSchema, 'GU-Socks'),
    GT: mongoose.model('GT-Socks', SocksSchema, 'GT-Socks'),
    GG: mongoose.model('GG-Socks', SocksSchema, 'GG-Socks'),
    GN: mongoose.model('GN-Socks', SocksSchema, 'GN-Socks'),
    GW: mongoose.model('GW-Socks', SocksSchema, 'GW-Socks'),
    GY: mongoose.model('GY-Socks', SocksSchema, 'GY-Socks'),
    HT: mongoose.model('HT-Socks', SocksSchema, 'HT-Socks'),
    HN: mongoose.model('HN-Socks', SocksSchema, 'HN-Socks'),
    HK: mongoose.model('HK-Socks', SocksSchema, 'HK-Socks'),
    HU: mongoose.model('HU-Socks', SocksSchema, 'HU-Socks'),
    IS: mongoose.model('IS-Socks', SocksSchema, 'IS-Socks'),
    IN: mongoose.model('IN-Socks', SocksSchema, 'IN-Socks'),
    ID: mongoose.model('ID-Socks', SocksSchema, 'ID-Socks'),
    IR: mongoose.model('IR-Socks', SocksSchema, 'IR-Socks'),
    IQ: mongoose.model('IQ-Socks', SocksSchema, 'IQ-Socks'),
    IE: mongoose.model('IE-Socks', SocksSchema, 'IE-Socks'),
    IM: mongoose.model('IM-Socks', SocksSchema, 'IM-Socks'),
    IL: mongoose.model('IL-Socks', SocksSchema, 'IL-Socks'),
    IT: mongoose.model('IT-Socks', SocksSchema, 'IT-Socks'),
    CI: mongoose.model('CI-Socks', SocksSchema, 'CI-Socks'),
    JM: mongoose.model('JM-Socks', SocksSchema, 'JM-Socks'),
    JP: mongoose.model('JP-Socks', SocksSchema, 'JP-Socks'),
    JE: mongoose.model('JE-Socks', SocksSchema, 'JE-Socks'),
    JO: mongoose.model('JO-Socks', SocksSchema, 'JO-Socks'),
    KZ: mongoose.model('KZ-Socks', SocksSchema, 'KZ-Socks'),
    KE: mongoose.model('KE-Socks', SocksSchema, 'KE-Socks'),
    KI: mongoose.model('KI-Socks', SocksSchema, 'KI-Socks'),
    XK: mongoose.model('XK-Socks', SocksSchema, 'XK-Socks'),
    KW: mongoose.model('KW-Socks', SocksSchema, 'KW-Socks'),
    KG: mongoose.model('KG-Socks', SocksSchema, 'KG-Socks'),
    LA: mongoose.model('LA-Socks', SocksSchema, 'LA-Socks'),
    LV: mongoose.model('LV-Socks', SocksSchema, 'LV-Socks'),
    LB: mongoose.model('LB-Socks', SocksSchema, 'LB-Socks'),
    LS: mongoose.model('LS-Socks', SocksSchema, 'LS-Socks'),
    LR: mongoose.model('LR-Socks', SocksSchema, 'LR-Socks'),
    LY: mongoose.model('LY-Socks', SocksSchema, 'LY-Socks'),
    LI: mongoose.model('LI-Socks', SocksSchema, 'LI-Socks'),
    LT: mongoose.model('LT-Socks', SocksSchema, 'LT-Socks'),
    LU: mongoose.model('LU-Socks', SocksSchema, 'LU-Socks'),
    MO: mongoose.model('MO-Socks', SocksSchema, 'MO-Socks'),
    MK: mongoose.model('MK-Socks', SocksSchema, 'MK-Socks'),
    MG: mongoose.model('MG-Socks', SocksSchema, 'MG-Socks'),
    MW: mongoose.model('MW-Socks', SocksSchema, 'MW-Socks'),
    MY: mongoose.model('MY-Socks', SocksSchema, 'MY-Socks'),
    MV: mongoose.model('MV-Socks', SocksSchema, 'MV-Socks'),
    ML: mongoose.model('ML-Socks', SocksSchema, 'ML-Socks'),
    MT: mongoose.model('MT-Socks', SocksSchema, 'MT-Socks'),
    MH: mongoose.model('MH-Socks', SocksSchema, 'MH-Socks'),
    MR: mongoose.model('MR-Socks', SocksSchema, 'MR-Socks'),
    MU: mongoose.model('MU-Socks', SocksSchema, 'MU-Socks'),
    YT: mongoose.model('YT-Socks', SocksSchema, 'YT-Socks'),
    MX: mongoose.model('MX-Socks', SocksSchema, 'MX-Socks'),
    FM: mongoose.model('FM-Socks', SocksSchema, 'FM-Socks'),
    MD: mongoose.model('MD-Socks', SocksSchema, 'MD-Socks'),
    MC: mongoose.model('MC-Socks', SocksSchema, 'MC-Socks'),
    MN: mongoose.model('MN-Socks', SocksSchema, 'MN-Socks'),
    ME: mongoose.model('ME-Socks', SocksSchema, 'ME-Socks'),
    MS: mongoose.model('MS-Socks', SocksSchema, 'MS-Socks'),
    MA: mongoose.model('MA-Socks', SocksSchema, 'MA-Socks'),
    MZ: mongoose.model('MZ-Socks', SocksSchema, 'MZ-Socks'),
    MM: mongoose.model('MM-Socks', SocksSchema, 'MM-Socks'),
    NA: mongoose.model('NA-Socks', SocksSchema, 'NA-Socks'),
    NR: mongoose.model('NR-Socks', SocksSchema, 'NR-Socks'),
    NP: mongoose.model('NP-Socks', SocksSchema, 'NP-Socks'),
    NL: mongoose.model('NL-Socks', SocksSchema, 'NL-Socks'),
    AN: mongoose.model('AN-Socks', SocksSchema, 'AN-Socks'),
    NC: mongoose.model('NC-Socks', SocksSchema, 'NC-Socks'),
    NZ: mongoose.model('NZ-Socks', SocksSchema, 'NZ-Socks'),
    NI: mongoose.model('NI-Socks', SocksSchema, 'NI-Socks'),
    NE: mongoose.model('NE-Socks', SocksSchema, 'NE-Socks'),
    NG: mongoose.model('NG-Socks', SocksSchema, 'NG-Socks'),
    NU: mongoose.model('NU-Socks', SocksSchema, 'NU-Socks'),
    KP: mongoose.model('KP-Socks', SocksSchema, 'KP-Socks'),
    MP: mongoose.model('MP-Socks', SocksSchema, 'MP-Socks'),
    NO: mongoose.model('NO-Socks', SocksSchema, 'NO-Socks'),
    OM: mongoose.model('OM-Socks', SocksSchema, 'OM-Socks'),
    PK: mongoose.model('PK-Socks', SocksSchema, 'PK-Socks'),
    PW: mongoose.model('PW-Socks', SocksSchema, 'PW-Socks'),
    PS: mongoose.model('PS-Socks', SocksSchema, 'PS-Socks'),
    PA: mongoose.model('PA-Socks', SocksSchema, 'PA-Socks'),
    PG: mongoose.model('PG-Socks', SocksSchema, 'PG-Socks'),
    PY: mongoose.model('PY-Socks', SocksSchema, 'PY-Socks'),
    PE: mongoose.model('PE-Socks', SocksSchema, 'PE-Socks'),
    PH: mongoose.model('PH-Socks', SocksSchema, 'PH-Socks'),
    PN: mongoose.model('PN-Socks', SocksSchema, 'PN-Socks'),
    PL: mongoose.model('PL-Socks', SocksSchema, 'PL-Socks'),
    PT: mongoose.model('PT-Socks', SocksSchema, 'PT-Socks'),
    PR: mongoose.model('PR-Socks', SocksSchema, 'PR-Socks'),
    QA: mongoose.model('QA-Socks', SocksSchema, 'QA-Socks'),
    CG: mongoose.model('CG-Socks', SocksSchema, 'CG-Socks'),
    RE: mongoose.model('RE-Socks', SocksSchema, 'RE-Socks'),
    RO: mongoose.model('RO-Socks', SocksSchema, 'RO-Socks'),
    RU: mongoose.model('RU-Socks', SocksSchema, 'RU-Socks'),
    RW: mongoose.model('RW-Socks', SocksSchema, 'RW-Socks'),
    BL: mongoose.model('BL-Socks', SocksSchema, 'BL-Socks'),
    SH: mongoose.model('SH-Socks', SocksSchema, 'SH-Socks'),
    KN: mongoose.model('KN-Socks', SocksSchema, 'KN-Socks'),
    LC: mongoose.model('LC-Socks', SocksSchema, 'LC-Socks'),
    MF: mongoose.model('MF-Socks', SocksSchema, 'MF-Socks'),
    PM: mongoose.model('PM-Socks', SocksSchema, 'PM-Socks'),
    VC: mongoose.model('VC-Socks', SocksSchema, 'VC-Socks'),
    WS: mongoose.model('WS-Socks', SocksSchema, 'WS-Socks'),
    SM: mongoose.model('SM-Socks', SocksSchema, 'SM-Socks'),
    ST: mongoose.model('ST-Socks', SocksSchema, 'ST-Socks'),
    SA: mongoose.model('SA-Socks', SocksSchema, 'SA-Socks'),
    SN: mongoose.model('SN-Socks', SocksSchema, 'SN-Socks'),
    RS: mongoose.model('RS-Socks', SocksSchema, 'RS-Socks'),
    SC: mongoose.model('SC-Socks', SocksSchema, 'SC-Socks'),
    SL: mongoose.model('SL-Socks', SocksSchema, 'SL-Socks'),
    SG: mongoose.model('SG-Socks', SocksSchema, 'SG-Socks'),
    SX: mongoose.model('SX-Socks', SocksSchema, 'SX-Socks'),
    SK: mongoose.model('SK-Socks', SocksSchema, 'SK-Socks'),
    SI: mongoose.model('SI-Socks', SocksSchema, 'SI-Socks'),
    SB: mongoose.model('SB-Socks', SocksSchema, 'SB-Socks'),
    SO: mongoose.model('SO-Socks', SocksSchema, 'SO-Socks'),
    ZA: mongoose.model('ZA-Socks', SocksSchema, 'ZA-Socks'),
    KR: mongoose.model('KR-Socks', SocksSchema, 'KR-Socks'),
    SS: mongoose.model('SS-Socks', SocksSchema, 'SS-Socks'),
    ES: mongoose.model('ES-Socks', SocksSchema, 'ES-Socks'),
    LK: mongoose.model('LK-Socks', SocksSchema, 'LK-Socks'),
    SD: mongoose.model('SD-Socks', SocksSchema, 'SD-Socks'),
    SR: mongoose.model('SR-Socks', SocksSchema, 'SR-Socks'),
    SJ: mongoose.model('SJ-Socks', SocksSchema, 'SJ-Socks'),
    SZ: mongoose.model('SZ-Socks', SocksSchema, 'SZ-Socks'),
    SE: mongoose.model('SE-Socks', SocksSchema, 'SE-Socks'),
    CH: mongoose.model('CH-Socks', SocksSchema, 'CH-Socks'),
    SY: mongoose.model('SY-Socks', SocksSchema, 'SY-Socks'),
    TW: mongoose.model('TW-Socks', SocksSchema, 'TW-Socks'),
    TJ: mongoose.model('TJ-Socks', SocksSchema, 'TJ-Socks'),
    TZ: mongoose.model('TZ-Socks', SocksSchema, 'TZ-Socks'),
    TH: mongoose.model('TH-Socks', SocksSchema, 'TH-Socks'),
    TG: mongoose.model('TG-Socks', SocksSchema, 'TG-Socks'),
    TK: mongoose.model('TK-Socks', SocksSchema, 'TK-Socks'),
    TO: mongoose.model('TO-Socks', SocksSchema, 'TO-Socks'),
    TT: mongoose.model('TT-Socks', SocksSchema, 'TT-Socks'),
    TN: mongoose.model('TN-Socks', SocksSchema, 'TN-Socks'),
    TR: mongoose.model('TR-Socks', SocksSchema, 'TR-Socks'),
    TM: mongoose.model('TM-Socks', SocksSchema, 'TM-Socks'),
    TC: mongoose.model('TC-Socks', SocksSchema, 'TC-Socks'),
    TV: mongoose.model('TV-Socks', SocksSchema, 'TV-Socks'),
    VI: mongoose.model('VI-Socks', SocksSchema, 'VI-Socks'),
    UG: mongoose.model('UG-Socks', SocksSchema, 'UG-Socks'),
    UA: mongoose.model('UA-Socks', SocksSchema, 'UA-Socks'),
    AE: mongoose.model('AE-Socks', SocksSchema, 'AE-Socks'),
    GB: mongoose.model('GB-Socks', SocksSchema, 'GB-Socks'),
    US: mongoose.model('US-Socks', SocksSchema, 'US-Socks'),
    UY: mongoose.model('UY-Socks', SocksSchema, 'UY-Socks'),
    UZ: mongoose.model('UZ-Socks', SocksSchema, 'UZ-Socks'),
    VU: mongoose.model('VU-Socks', SocksSchema, 'VU-Socks'),
    VA: mongoose.model('VA-Socks', SocksSchema, 'VA-Socks'),
    VE: mongoose.model('VE-Socks', SocksSchema, 'VE-Socks'),
    VN: mongoose.model('VN-Socks', SocksSchema, 'VN-Socks'),
    WF: mongoose.model('WF-Socks', SocksSchema, 'WF-Socks'),
    EH: mongoose.model('EH-Socks', SocksSchema, 'EH-Socks'),
    YE: mongoose.model('YE-Socks', SocksSchema, 'YE-Socks'),
    ZM: mongoose.model('ZM-Socks', SocksSchema, 'ZM-Socks'),
    ZW: mongoose.model('ZW-Socks', SocksSchema, 'ZW-Socks')
};
